### ISSUE TITLE
Make numbers in the manuscript dynamic

### ISSUE THREAD

**Issue by chartgerink** [chartgerink/2016marginal#13]
In order to increase reproducibility, please include the code that generates the numbers in for example the method section. That way there is less room for human error and if anything changes in the data, it takes you less time. You can include code relatively easy (see [cheatsheet](www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf)

This is a suggestion, not a requirement.

**Comment by Jaeoc** [comment]
So the only reasons I haven't done this yet is that is that i) I find the resulting number format less legible (i.e. becomes 790206 instead of 790,206) and ii) the largeness of the dataset will really slow down knitting of the document.

Any thoughts on this?

**Comment by chartgerink** [comment]
The file is 21.7MB right? If you setup everything with the testset (way smaller) I can imagine you just add the Rmarkdown code and rerun with general set when the time comes. Maybe try and see what the runtime is if you load in the data and the runtime without?

I can imagine it is maybe a difference of a few seconds, not minutes. But if you prefer not to, that's okay as well. It is also possible to do it at the end (I just think it'll save you time in the long run).

Ps. The format can always be adjusted at the final stage if you really want it to be 790,206 instead of 790206)

**Comment by Jaeoc** [comment]
Since the method section requires a lot of values from the full data-set it's the one that 300+ MB something, but I just tried it out and it's not too bad actually. I'll see how it goes.

**Comment by chartgerink** [comment]
Ah like that. What you could do is just compute the relevant numbers in a script, save the object that contains all of that (e.g., in a list) with `save()` and then load it in the Rmd file `load()`. Then you don't need to load in the 300MB file. :godmode:

**Comment by Jaeoc** [comment]
Hmm, could be a good way to do it. Then I could do the same with the tables, which would otherwise lead to the .rmd containing a huge amount of code, so should make it more legible.

**Comment by Jaeoc** [comment]
Works great!
