### ISSUE TITLE
Treatment of comparison signs in extraction

### ISSUE THREAD

**Issue by Jaeoc** [chartgerink/2016marginal#17]
@chartgerink 

I was looking through your readme and functions to see how you treated the "≥" and "≤" signs in extraction, but it is not clear to me. Did you just replace them with ">" and "<" signs? (Since we only have =/</> signs in the dataset)

**Comment by chartgerink** [comment]
Good question, didn't know anymore but just checked and the code is right [here](https://github.com/chartgerink/2016marginal/blob/master/functions/data_extraction.R#L17).

```R
txt <- gsub(pattern = '_', replacement = '', x = txt)
txt <- gsub(pattern = '&lt;', replacement = '<', x = txt)
txt <- gsub(pattern = '&gt;', replacement = '>', x = txt)
    
locs <- str_locate_all(pattern = "\\sp\\s*[=<>]\\s*\\d?\\.\\d*", txt)[[1]]
```

So all `&lt;` and `&gt;` are replaced. Specifically for the cases you ask about, these are not included. Why? I don't know anymore, but post hoc I can say that reporting (e.g.) p <= .064 makes no sense except when reporting a set of results. You can simply mention what we did and that we looked at [=<>]

**Comment by Jaeoc** [comment]
Hmm, yeah, good point. I guess I could imagine someone reporting that "all other results were marginally significant p<= .1", but seems like it would only be relevant for a very small minority of values. I'll just report what we did then
