### ISSUE TITLE
Q: inline referencing detail

### ISSUE THREAD

**Issue by Jaeoc** [chartgerink/2016marginal#23]
@chartgerink 

Can't figure out how to get the ; after 2016 in the line below:

> Pritschet, Powell, & Horne (2016; available at https://osf.io/92xqk/)

Closest I get is with a , instead of the ; when I use the following:
`@10.1177/0956797616645672 [available at https://osf.io/92xqk/]`
>Pritschet, Powell, & Horne (2016, available at https://osf.io/92xqk/)

Any idea?

**Comment by chartgerink** [comment]
Sometimes Rmarkdown is finnicky, yes. It's a relatively recent development, so sometimes it isn't yet able to do exactly what you want it to. See also [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citations) for more citation syntax. I'd say, go for what you have here, don't necessarily need the `;`.
