### ISSUE TITLE
Q: invalid file path

### ISSUE THREAD

**Issue by Jaeoc** [chartgerink/2016marginal#3]
@chartgerink 

- [x] Certain meta-data files contain a colon, which then makes them invalid as file names on Windows, with the consequence that I cannot clone the repo to my laptop. How to solve this?

**Comment by chartgerink** [comment]
I replaced `data/metadata/` with `data/metadata.zip` which should resolve the issue. Can you retry cloning the repo?

Wiley tends to have weird DOIs and I had not realized these could mess with the path on Windows, my bad.

**Comment by Jaeoc** [comment]
Great, now it works. Thanks!
