### ISSUE TITLE
Creation of smaller sample

### ISSUE THREAD

**Issue by Jaeoc** [chartgerink/2016marginal#6]
@chartgerink 

1.  I'm a little confused about the best smaller sample to create to try out script, what are your thoughts on this? The best option as far as I can see would be to do a stratified random sample from the different topics. As far as I understood, however, Marcel suggested we create a different data file for each APA-topic, and then use one of these as the smaller sample? Just not sure how this would go together with us then being able to claim the script works for all topics as he also suggested? Perhaps I misunderstood, nonetheless, seems disadvantageous to create separate files considering the overlap between topics.

2. I've noticed there is a small number of missing (p-)values in the dataset. Moreover, we are only interested in results for .05 < p <= .1. It seems to me that the most reasonable is to remove the NA-values, and limit the dataset to the relevant p-values before creating the test sample (to be able to estimate the proportion of NA-values, and not create a test sample where we then remove >90% of the values). Any good reason not to do so? 

3.  Also, any suggestion for an efficient way to gather the names of all journals in different topics from APA (web scraping somehow?), or should I just do it manually?

**Comment by chartgerink** [comment]
1. I suggest you write the code to select out all irrelevant data first, then look up the sample function to sample random rows from the remaining dataset. I can do that to keep you blind. It will look something like this
```R
dat <- read.csv(file)
dat <- dat[dat$pval >= .05 & dat$pval <= .10 & dat$comparison == '=',]
sel <- sample(1:dim(dat)[1], replace = FALSE)
write.csv(dat[sel, ], 'testset.csv', row.names = FALSE)
```

2. Yes this is the data cleaning that needs to be done. If it are _many_ values, please inspect and if there is something obvious going on drop it in the issues to discuss

3. No tricks that would be faster given the highly specific task (any scripts wouldn't really be reusable at first glance)

**Comment by Jaeoc** [comment]
Got stuck for a while on some points with the cleaning, so took me a while longer than expected. I'm about to pull the test sample, but was wondering if you have a suggestion on how to decide on size? i.e. I was thinking of just taking a sample of 1000 rows, but don't really have a reason for doing that instead of e.g. 500 or 2000. The trimmed dataset (.05 < p <= .1) is about 50k rows.

**Comment by chartgerink** [comment]
These choices are often arbitrary so don't look for too much reason behind that. 

I would suggest that there should be enough variation in the sampled data so the analyses can run (e.g., have enough from the different journals) and that you won't be testing scripts on a biased set of data. 500 (1%), 2500 (5%), 5000 (10%), you can find a reason for all of them. In the end, you'll just have to make a choice to test the script on (just don't go beyond 10% I'd say).
